# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='BoardUpdateMessage.proto',
  package='Messaging',
  serialized_pb=b'\n\x18\x42oardUpdateMessage.proto\x12\tMessaging\"\xc6\x01\n\x12\x42oardUpdateMessage\x12>\n\x0csquare_infos\x18\x01 \x03(\x0b\x32(.Messaging.BoardUpdateMessage.SquareInfo\x1ap\n\nSquareInfo\x12\x15\n\rsquare_number\x18\x01 \x01(\x05\x12\x1b\n\x13owner_player_number\x18\x02 \x01(\x05\x12\x14\n\x0cis_mortgaged\x18\x03 \x01(\x08\x12\x18\n\x10number_of_houses\x18\x04 \x01(\x05')




_BOARDUPDATEMESSAGE_SQUAREINFO = descriptor.Descriptor(
  name='SquareInfo',
  full_name='Messaging.BoardUpdateMessage.SquareInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='square_number', full_name='Messaging.BoardUpdateMessage.SquareInfo.square_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='owner_player_number', full_name='Messaging.BoardUpdateMessage.SquareInfo.owner_player_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_mortgaged', full_name='Messaging.BoardUpdateMessage.SquareInfo.is_mortgaged', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='number_of_houses', full_name='Messaging.BoardUpdateMessage.SquareInfo.number_of_houses', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=238,
)

_BOARDUPDATEMESSAGE = descriptor.Descriptor(
  name='BoardUpdateMessage',
  full_name='Messaging.BoardUpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='square_infos', full_name='Messaging.BoardUpdateMessage.square_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BOARDUPDATEMESSAGE_SQUAREINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=238,
)

_BOARDUPDATEMESSAGE_SQUAREINFO.containing_type = _BOARDUPDATEMESSAGE;
_BOARDUPDATEMESSAGE.fields_by_name['square_infos'].message_type = _BOARDUPDATEMESSAGE_SQUAREINFO
DESCRIPTOR.message_types_by_name['BoardUpdateMessage'] = _BOARDUPDATEMESSAGE

BoardUpdateMessage = reflection.GeneratedProtocolMessageType('BoardUpdateMessage', (message.Message,),
    {
      'DESCRIPTOR': _BOARDUPDATEMESSAGE,
      'SquareInfo': reflection.GeneratedProtocolMessageType('SquareInfo', (message.Message,),
          {
            'DESCRIPTOR': _BOARDUPDATEMESSAGE_SQUAREINFO,
            # @@protoc_insertion_point(class_scope:Messaging.BoardUpdateMessage.SquareInfo)
          }),
      # @@protoc_insertion_point(class_scope:Messaging.BoardUpdateMessage)
    })

# @@protoc_insertion_point(module_scope)
