# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='PlayerInfoMessage.proto',
  package='Messaging',
  serialized_pb=b'\n\x17PlayerInfoMessage.proto\x12\tMessaging\"\xc2\x01\n\x11PlayerInfoMessage\x12=\n\x0cplayer_infos\x18\x01 \x03(\x0b\x32\'.Messaging.PlayerInfoMessage.PlayerInfo\x1an\n\nPlayerInfo\x12\x15\n\rplayer_number\x18\x01 \x01(\x05\x12\x11\n\tnet_worth\x18\x02 \x01(\x05\x12\x11\n\tgames_won\x18\x03 \x01(\x05\x12\x13\n\x0bms_per_turn\x18\x04 \x01(\x01\x12\x0e\n\x06square\x18\x05 \x01(\x05')




_PLAYERINFOMESSAGE_PLAYERINFO = descriptor.Descriptor(
  name='PlayerInfo',
  full_name='Messaging.PlayerInfoMessage.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='player_number', full_name='Messaging.PlayerInfoMessage.PlayerInfo.player_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='net_worth', full_name='Messaging.PlayerInfoMessage.PlayerInfo.net_worth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='games_won', full_name='Messaging.PlayerInfoMessage.PlayerInfo.games_won', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ms_per_turn', full_name='Messaging.PlayerInfoMessage.PlayerInfo.ms_per_turn', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='square', full_name='Messaging.PlayerInfoMessage.PlayerInfo.square', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=233,
)

_PLAYERINFOMESSAGE = descriptor.Descriptor(
  name='PlayerInfoMessage',
  full_name='Messaging.PlayerInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='player_infos', full_name='Messaging.PlayerInfoMessage.player_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PLAYERINFOMESSAGE_PLAYERINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=233,
)

_PLAYERINFOMESSAGE_PLAYERINFO.containing_type = _PLAYERINFOMESSAGE;
_PLAYERINFOMESSAGE.fields_by_name['player_infos'].message_type = _PLAYERINFOMESSAGE_PLAYERINFO
DESCRIPTOR.message_types_by_name['PlayerInfoMessage'] = _PLAYERINFOMESSAGE

PlayerInfoMessage = reflection.GeneratedProtocolMessageType('PlayerInfoMessage', (message.Message,),
    {
      'DESCRIPTOR': _PLAYERINFOMESSAGE,
      'PlayerInfo': reflection.GeneratedProtocolMessageType('PlayerInfo', (message.Message,),
          {
            'DESCRIPTOR': _PLAYERINFOMESSAGE_PLAYERINFO,
            # @@protoc_insertion_point(class_scope:Messaging.PlayerInfoMessage.PlayerInfo)
          }),
      # @@protoc_insertion_point(class_scope:Messaging.PlayerInfoMessage)
    })

# @@protoc_insertion_point(module_scope)
