# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='StartOfTournamentMessage.proto',
  package='Messaging',
  serialized_pb=b'\n\x1eStartOfTournamentMessage.proto\x12\tMessaging\"0\n\x18StartOfTournamentMessage\x12\x14\n\x0cplayer_names\x18\x01 \x03(\t')




_STARTOFTOURNAMENTMESSAGE = descriptor.Descriptor(
  name='StartOfTournamentMessage',
  full_name='Messaging.StartOfTournamentMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='player_names', full_name='Messaging.StartOfTournamentMessage.player_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['StartOfTournamentMessage'] = _STARTOFTOURNAMENTMESSAGE

StartOfTournamentMessage = reflection.GeneratedProtocolMessageType('StartOfTournamentMessage', (message.Message,),
    {
      'DESCRIPTOR': _STARTOFTOURNAMENTMESSAGE,
      # @@protoc_insertion_point(class_scope:Messaging.StartOfTournamentMessage)
    })

# @@protoc_insertion_point(module_scope)
