//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerInfoMessage.proto
namespace Messaging
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfoMessage")]
  public partial class PlayerInfoMessage : global::ProtoBuf.IExtensible
  {
    public PlayerInfoMessage() {}
    
    private readonly global::System.Collections.Generic.List<Messaging.PlayerInfoMessage.PlayerInfo> _player_infos = new global::System.Collections.Generic.List<Messaging.PlayerInfoMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Messaging.PlayerInfoMessage.PlayerInfo> player_infos
    {
      get { return _player_infos; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _player_number = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_number
    {
      get { return _player_number; }
      set { _player_number = value; }
    }
    private int _net_worth = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"net_worth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int net_worth
    {
      get { return _net_worth; }
      set { _net_worth = value; }
    }
    private int _games_won = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"games_won", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int games_won
    {
      get { return _games_won; }
      set { _games_won = value; }
    }
    private double _ms_per_turn = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ms_per_turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ms_per_turn
    {
      get { return _ms_per_turn; }
      set { _ms_per_turn = value; }
    }
    private int _square = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"square", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int square
    {
      get { return _square; }
      set { _square = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}