//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StartOfTournamentMessage.proto
namespace Messaging
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartOfTournamentMessage")]
  public partial class StartOfTournamentMessage : global::ProtoBuf.IExtensible
  {
    public StartOfTournamentMessage() {}
    
    private readonly global::System.Collections.Generic.List<string> _player_names = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> player_names
    {
      get { return _player_names; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}