from .square import Square
from .go import Go
from .property import Property
from .street import Street
from .community_chest import CommunityChest
from .tax import Tax
from .station import Station
from .chance import Chance
from .jail import Jail
from .utility import Utility
from .free_parking import FreeParking
from .go_to_jail import GoToJail
